rpadutils/rpadutils.py

I demand we keep the name tho :0

RPadUtils can now be a package

---

donations/donations.py

run "^donations setup @Donor @Patron" after you load this

Donations globalization

---

trigger/trigger.py

I think I get a free t-shirt for sending this PR which is rad

Show enabled channels on trigger info

---

globalban/globalban.py
requirements.txt

Remember globalban banlist

---

emojicog/emojicog.py

It can now take a message link or a message with some number of emoji in it.

Removed strict stealemoji input requirements

---

automod2/automod2.py

https://github.com/TsubakiBotPad/pad-cogs/issues/659

Add eyes to automod2

---

friend/__init__.py
friend/friend.py
friend/info.json

resolves https://github.com/TsubakiBotPad/pad-cogs/issues/466

Add Friend cog

---

grantrole/grantrole.py

~~Adding role to self is surprisingly not one of the features of selfrole~~ 
I forgot the name of my own cog

make grantrole catchup not give roles to bot

---

automod2/automod2.py
msgutils/msgutils.py

Messages will only be checked if they were created/sent in the last 300 seconds. 
(ignore the revert I messed with something I shouldn't have and deleted it)

Gate automod2 imagelimit to be time-based

---

speech/speech.py

It just... didn't take in self?  It has to take in self.

[speech] Make `valid_keys` work

---

translate/translate.py

This is such a helpful command omg I keep writing this and not pushing it

Add ^translate

---

baduser/baduser.py

Don't shout when a banned user can't be contacted

---

timecog/timecog.py

Implement remindmehere

---

automod2/automod2.py

Add channel args to automod2

---

baduser/baduser.py

Remove auto-striking for punishment roles

---

baduser/baduser.py

Add no-ping message when bad_role is removed

---

calculator/calculator.py

[Calculator] Enhance safety and ADD COMMAS!!!

---

menulistener/menulistener.py

Closes #156
Closes https://github.com/TsubakiBotPad/pad-cogs/issues/701
Closes https://github.com/TsubakiBotPad/discord-menu/issues/25

Allow menulistener to listen to older messages

---

menulistener/menulistener.py

Part of https://github.com/TsubakiBotPad/pad-cogs/pull/1099

[MenuListener] Make child data func async

---

menulistener/menulistener.py

Resolves https://github.com/TsubakiBotPad/pad-cogs/issues/1117

Read child menu type dynamically from ims

---

trigger/trigger.py

oh my god we've had this issue (that effects nobody but me) for so long

Trigger - fix catch condition

---

onlineplot/onlineplot.py
timecog/__init__.py

Count weeks in OnlinePlot title

---

onlineplot/onlineplot.py

Warn if no data is found in OnlinePlot

---

onlineplot/onlineplot.py

[OnlinePlot] Delete data on optout

---

timecog/timecog.py

Completely anonymous removal of a space.

Removed double space

---

automod/automod.py

[Automod] Adjust config object naming

---

timecog/timecog.py

Added rm, delete, del aliases for remove subcommand in ^remindme

Add remindme aliases for remove

---

timecog/timecog.py

Closes #42: Time zone can now be hidden when adding a remindme or pulling up the list of pending reminders.

Added toggletzprivate subcommand to remindme

---

automod/automod.py

Add a single f to fix formatting strings in watchdog

---

grantrole/grantrole.py

Select language for emoji

---

menulistener/menulistener.py

Partially closes https://github.com/TsubakiBotPad/discord-menu/issues/21

Support tuples of emojis with fallbacks

---

devutils/devutils.py

Stop pipupdate from DMing user

---

timecog/timecog.py

Add UTC timezones to timecog

---

stickers/stickers.py

I was gonna retire this cog, but look at these stickers!!!!!

Fix sticker cog

---

onlineplot/onlineplot.py

Make onlineplot work on Sundays

---

timecog/timecog.py

Fix NA timezone

---

modtools/modtools.py

Lists all users with a specified string in their username (alias ^usersearch)
Resolves #249

Added ^usernamesearch

---

sqlactivitylog/sqlactivitylog.py

Make SQLActivityLog Shut Up

---

replylistener/info.json
replylistener/replylistener.py
sqlactivitylog/sqlactivitylog.py

Closes https://github.com/RheingoldRiver/esports-wiki-cogs/issues/56

Make exlog shut up

---

devutils/devutils.py

Send the output of pipupdate

---

grantrole/grantrole.py

Catch discord.Forbidden in ^grantrole onreact serverlist

---

selfroleoverride/selfroleoverride.py

Bot was assigning/removing roles not on the selfrole list oh no

Patch invalid selfrole assignments

---

devutils/devutils.py

Delaycommand, check if emptystring not None

---

automod/automod.py
linklistener/linklistener.py

Fix automod and linklistener

---

msgutils/msgutils.py

Reverts TsubakiBotPad/misc-cogs#309

Revert "Make channel optional in editmsg and dumpmsg"

---

baduser/baduser.py
baduser/baduser_helper.py

it was because avatar_url isn't a property in red3.5dev
also fixes `^baduser report`

Fix baduser embed

---

twitterlistener/__init__.py
twitterlistener/info.json
twitterlistener/twitterlistener.py

Resolves #307 
Works with tweets with multiple images and when multiple tweets are in the same message (who does this though)
Not sure if the twitter link should be shortened into [Twitter Link] or keep it as the full link

Add Twitter Listener

---

fancysay/fancysay.py

Allow ^fancysay emoji & tdif in DMs

---

linklistener/linklistener.py

ignore wrapped links

---

baduser/baduser_helper.py

Reverse order of messages in baduser latest messages

---

automod/automod.py

Imgur no longer allows uploading images from a mobile browser.

Edit endimagespam message

---

automod/automod.py

Similar to imagelimit, prevent users from posting messages with more than some number of attached embeds.
(the message could probably be changed to something more helpful)

Add embedlimit

---

baduser/baduser_helper.py

Fix showing avatars in baduser reports
